"""
QNS - Quantum Noise Symbiote
Type stubs for IDE support.
"""
from __future__ import annotations
from typing import Dict, List, Optional, Tuple, Any

__version__: str
__author__: str

class Gate:
    """Quantum gate representation."""
    
    @staticmethod
    def h(qubit: int) -> Gate: ...
    @staticmethod
    def x(qubit: int) -> Gate: ...
    @staticmethod
    def y(qubit: int) -> Gate: ...
    @staticmethod
    def z(qubit: int) -> Gate: ...
    @staticmethod
    def s(qubit: int) -> Gate: ...
    @staticmethod
    def t(qubit: int) -> Gate: ...
    @staticmethod
    def rx(qubit: int, theta: float) -> Gate: ...
    @staticmethod
    def ry(qubit: int, theta: float) -> Gate: ...
    @staticmethod
    def rz(qubit: int, theta: float) -> Gate: ...
    @staticmethod
    def cnot(control: int, target: int) -> Gate: ...
    @staticmethod
    def cz(control: int, target: int) -> Gate: ...
    @staticmethod
    def swap(qubit1: int, qubit2: int) -> Gate: ...
    @staticmethod
    def measure(qubit: int) -> Gate: ...
    
    @property
    def name(self) -> str: ...
    @property
    def qubits(self) -> List[int]: ...
    @property
    def is_two_qubit(self) -> bool: ...
    @property
    def angle(self) -> Optional[float]: ...
    @property
    def estimated_error(self) -> float: ...
    
    def commutes_with(self, other: Gate) -> bool: ...


class Circuit:
    """Quantum circuit representation."""
    
    def __init__(self, num_qubits: int) -> None: ...
    
    @property
    def num_qubits(self) -> int: ...
    @property
    def depth(self) -> int: ...
    @property
    def two_qubit_count(self) -> int: ...
    @property
    def gates(self) -> List[Gate]: ...
    
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Gate: ...
    
    def add_gate(self, gate: Gate) -> None: ...
    def h(self, qubit: int) -> None: ...
    def x(self, qubit: int) -> None: ...
    def y(self, qubit: int) -> None: ...
    def z(self, qubit: int) -> None: ...
    def s(self, qubit: int) -> None: ...
    def t(self, qubit: int) -> None: ...
    def rx(self, qubit: int, theta: float) -> None: ...
    def ry(self, qubit: int, theta: float) -> None: ...
    def rz(self, qubit: int, theta: float) -> None: ...
    def cnot(self, control: int, target: int) -> None: ...
    def cz(self, control: int, target: int) -> None: ...
    def swap(self, qubit1: int, qubit2: int) -> None: ...
    def measure(self, qubit: int) -> None: ...
    def measure_all(self) -> None: ...
    def copy(self) -> Circuit: ...
    def clear(self) -> None: ...
    def to_json(self) -> str: ...
    
    @staticmethod
    def from_json(json_str: str) -> Circuit: ...


class NoiseVector:
    """Noise parameters for a single qubit."""
    
    def __init__(
        self,
        qubit_id: int = 0,
        t1: float = 100.0,
        t2: float = 80.0,
        gate_error_1q: float = 0.001,
        gate_error_2q: float = 0.01,
        readout_error: float = 0.01,
    ) -> None: ...
    
    @property
    def qubit_id(self) -> int: ...
    @property
    def t1(self) -> float: ...
    @property
    def t2(self) -> float: ...
    @property
    def t_phi(self) -> Optional[float]: ...
    @property
    def gate_error_1q(self) -> float: ...
    @property
    def gate_error_2q(self) -> float: ...
    @property
    def readout_error(self) -> float: ...
    @property
    def t2_t1_ratio(self) -> float: ...
    
    def validate(self) -> None: ...
    def estimate_gate_fidelity(self, gate_time_ns: float, is_two_qubit: bool) -> float: ...


class NoiseModel:
    """Noise model for quantum simulation."""
    
    def __init__(
        self,
        t1: float = 100.0,
        t2: float = 80.0,
        gate_error_1q: float = 0.001,
        gate_error_2q: float = 0.01,
        readout_error: float = 0.01,
    ) -> None: ...
    
    @staticmethod
    def ideal() -> NoiseModel: ...
    
    @property
    def t1(self) -> float: ...
    @property
    def t2(self) -> float: ...
    @property
    def gate_error_1q(self) -> float: ...
    @property
    def gate_error_2q(self) -> float: ...
    @property
    def readout_error(self) -> float: ...
    
    def is_valid(self) -> bool: ...
    def to_noise_vector(self, qubit_id: int) -> NoiseVector: ...


class HardwareProfile:
    """Hardware topology and qubit properties."""
    
    @staticmethod
    def linear(name: str, num_qubits: int) -> HardwareProfile: ...
    @staticmethod
    def ring(name: str, num_qubits: int) -> HardwareProfile: ...
    @staticmethod
    def fully_connected(name: str, num_qubits: int) -> HardwareProfile: ...
    
    @property
    def name(self) -> str: ...
    @property
    def num_qubits(self) -> int: ...
    
    def are_connected(self, q1: int, q2: int) -> bool: ...
    def neighbors(self, qubit: int) -> List[int]: ...
    def coupling_map(self) -> List[Tuple[int, int]]: ...


class OptimizationResult:
    """Result of circuit optimization."""
    
    optimized_circuit: Circuit
    original_score: float
    optimized_score: float
    variants_explored: int
    optimization_time_ms: float
    algorithm: str
    
    @property
    def score_improvement(self) -> float: ...
    @property
    def score_delta(self) -> float: ...


class QnsOptimizer:
    """QNS noise-aware circuit optimizer."""
    
    def __init__(
        self,
        num_qubits: int,
        noise_model: Optional[NoiseModel] = None,
        beam_width: int = 10,
        max_iterations: int = 50,
    ) -> None: ...
    
    @property
    def num_qubits(self) -> int: ...
    @property
    def noise_vectors(self) -> List[NoiseVector]: ...
    
    def set_noise(self, noise: NoiseVector) -> None: ...
    def set_noise_model(self, noise_model: NoiseModel) -> None: ...
    def set_hardware(self, profile: HardwareProfile) -> None: ...
    def set_beam_params(self, beam_width: int, max_iterations: int) -> None: ...
    def set_auto_algorithm(self, auto: bool) -> None: ...
    def optimize(self, circuit: Circuit, use_beam_search: Optional[bool] = None) -> OptimizationResult: ...
    def score(self, circuit: Circuit) -> float: ...


class ExecutionResult:
    """Result of circuit execution."""
    
    @property
    def counts(self) -> Dict[str, int]: ...
    @property
    def shots(self) -> int: ...
    @property
    def execution_time_ms(self) -> float: ...
    @property
    def backend_name(self) -> str: ...
    
    def probabilities(self) -> Dict[str, float]: ...
    def most_frequent(self) -> Optional[Tuple[str, int]]: ...
    def get_count(self, bitstring: str) -> int: ...
    def get_probability(self, bitstring: str) -> float: ...


class CalibrationData:
    """Calibration data from a backend."""
    
    @property
    def noise_vectors(self) -> List[NoiseVector]: ...
    @property
    def timestamp(self) -> int: ...
    @property
    def source(self) -> str: ...
    @property
    def num_qubits(self) -> int: ...
    
    def get_qubit(self, qubit_id: int) -> NoiseVector: ...
    def avg_t1(self) -> float: ...
    def avg_t2(self) -> float: ...


class SimulatorBackend:
    """Quantum circuit simulator backend."""
    
    def __init__(
        self,
        num_qubits: int,
        noise_model: Optional[NoiseModel] = None,
        name: Optional[str] = None,
    ) -> None: ...
    
    @staticmethod
    def ideal(num_qubits: int) -> SimulatorBackend: ...
    
    @property
    def name(self) -> str: ...
    @property
    def num_qubits(self) -> int: ...
    @property
    def max_qubits(self) -> int: ...
    @property
    def supported_gates(self) -> List[str]: ...
    @property
    def supports_mid_circuit_measurement(self) -> bool: ...
    
    def run(self, circuit: Circuit, shots: int = 1024, mode: str = "sync") -> ExecutionResult: ...
    def calibration(self) -> CalibrationData: ...
    def topology(self) -> HardwareProfile: ...
    def set_noise(self, noise_model: NoiseModel) -> None: ...
    def is_available(self) -> bool: ...


def estimate_circuit_fidelity(circuit: Circuit, noise: NoiseVector) -> float:
    """Estimates circuit fidelity based on noise parameters."""
    ...

def score_circuit(circuit: Circuit, noise: NoiseVector) -> float:
    """Scores a circuit for noise-aware optimization."""
    ...


class convert:
    """Conversion utilities for Qiskit integration."""
    
    @staticmethod
    def circuit_to_qasm(circuit: Circuit) -> str: ...
    
    @staticmethod
    def circuit_from_qasm(qasm: str) -> Circuit: ...
    
    @staticmethod
    def circuit_to_dict(circuit: Circuit) -> Dict[str, Any]: ...
    
    @staticmethod
    def circuit_from_dict(d: Dict[str, Any]) -> Circuit: ...
